language: node_js

node_js: "8.11.3"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libavahi-compat-libdnssd-dev git
  - sudo apt-get install npm
  - sudo npm config set strict-ssl false
  - nvm install 8.11.3
  - nvm use 8.11.3
  - sudo npm install -g --unsafe-perm homebridge

before_script:
  - "sudo npm install -g homebridge-garage-door-wsensor"
  - "sudo cp config.sample.json .homebridge/config.json"

script: "sudo homebridge & sleep 30; kill $!;"

