language: node_js

env:
  - ARCH=arm

node_js: "8.11.3"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libavahi-compat-libdnssd-dev git
  - npm config set strict-ssl false
  - nvm install 8.11.3
  - nvm use 8.11.3
  - npm install -g --unsafe-perm homebridge
  - git clone git://github.com/quick2wire/quick2wire-gpio-admin.git
  - cd quick2wire-gpio-admin
  - make
  - sudo make install
  - sudo adduser $USER gpio
  - cd ../
  - sudo mkdir /sys/class
  - sudo mkdir /sys/class/gpio
  - sudo mkdir /sys/class/gpio/gpio15
  - sudo echo "0" > /sys/class/gpio/gpio15/value
  - sudo mkdir /sys/class/gpio/gpio17
  - sudo echo "0" > /sys/class/gpio/gpio17/value

before_script:
  - "npm install -g homebridge-garage-door-wsensor"
  - "mkdir /home/travis/.homebridge"
  - "cp config.sample.json /home/travis/.homebridge/config.json"

script: "homebridge & sleep 30; kill $!;"

